# Generated by Django 2.0.3 on 2018-03-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Categoria')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL')),
                ('target_blank', models.BooleanField(verbose_name='Abrir em nova janela')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
